### ISSUE TITLE
Make this a "real" C-style preprocessor?

### ISSUE THREAD

**Issue by glampert** [glampert/vclpp#3]
Hello,

I just noticed that some people are now watching this repository.

I coded this tool in a very ad hoc manner a while ago in one afternoon just to have a minimal preprocessor for OpenVCL and my Quake port, so it is not a very feature rich tool and not very flexible in the way macros have to be written. Worked for me, so I never gave much thought to it after writing the tool.

But since then I have actually written a "real" [C/C++ preprocessor](https://github.com/glampert/parse-utils) which could now be used to rewrite vclpp allowing the usage of the traditional macro syntax of C, with full support for `#ifdef` switches, etc.

Is that something people would be interested on? That is, replacing the current ad hoc syntax by a fully fledged C/C++ preprocessor?

If enough people find it useful, I can allocate some time to make the rewrite.

Thanks!

**Comment by tamara-schmitz** [comment]
As a PS2Dev noob I'd really appreciate a C-like (or GLSL-like) preprocessing language!
Assembly can quickly become quite messy.

**Comment by sk-io** [comment]
Doesn't openvcl already include a c preprocessor using -G?
